
[package]
name = "skillnet_exam"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.9.4"
openzeppelin = "1.0.0"

[dev-dependencies]
snforge_std = "0.39.0"
assert_macros = "^2.9.4"


[[target.starknet-contract]]
casm = true
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
